name: Build WebComponent

# Trigger the workflow on push to the 'main' branch and manually using workflow_dispatch
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Explicitly set permissions for the GITHUB_TOKEN
      packages: write

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js (use the version specified in .nvmrc or package.json)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'  # You can specify a version if needed

      # Step 3: Install dependencies using npm ci
      - name: Install dependencies
        run: npm ci

      # Step 4: Build the web component
      - name: Build web component
        run: npm run build:static

      # Step 5: Upload the build output (for artifacts or other actions)
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: webcomponent
          path: |
            static/excel-importer.mjs
            static/webcomponent.css
